# Parametric EQ profile for Dan Clark Closed-X, applies bass boost
#
# To activate, run $ pactl set-default-sink closed-x_eq_in
#
context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "DCA Closed-X Bass Boost"
            media.name       = "DCA Closed-X Bass Boost"
            filter.graph = {
                nodes = [
                    {
                        type  = builtin
                        name  = eq0
                        label = bq_highshelf
                        control = { "Freq" = 0.0 "Q" = 1 "Gain" = -6.0 }
                    }
                    {
                        type = builtin
                        name = eq1
                        label = bq_lowshelf
                        control = { "Freq" = 1000 "Q" = 0.1 "Gain" = 6.0 }
                    }
                    {
                        type = builtin
                        name = eq2
                        label = bq_highshelf
                        control = { "Freq" = 5000 "Q" = 1.0 "Gain" = -3.0 }
                    }
                ]
                links = [
                    { output = "eq0:Out" input = "eq1:In" }
                    { output = "eq1:Out" input = "eq2:In" }
                ]
            }
	        audio.channels = 2
	        audio.position = [ FL FR ]
            capture.props = {
                node.name   = "Closed-X_EQ_In"
                media.class = Audio/Sink
            }
            playback.props = {
                node.name   = "Closed-X_EQ_Out"
                node.passive = true
            }
        }
    }
]
