# Paramatric EQ for AFUL Explorer
#
# To activate, run $ pactl set-default-sink Explorer_in
#
context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "AFUL Explorer"
            media.name       = "AFUL Explorer"
            filter.graph = {
                nodes = [
                    {
                        type  = builtin
                        name  = eq0
                        label = bq_highshelf
                        control = { "Freq" = 0.0 "Q" = 1.0 "Gain" = -6.0 }
                    }
                    {
                        type = builtin
                        name = eq1
                        label = bq_peaking
                        control = { "Freq" = 7200 "Q" = 3.0 "Gain" = -3.0 }
                    }
                    {
                        type = builtin
                        name = eq2
                        label = bq_peaking
                        control = { "Freq" = 15500 "Q" = 2.0 "Gain" = 6.0 }
                    }
                ]
                links = [
                    { output = "eq0:Out" input = "eq1:In" }
                    { output = "eq1:Out" input = "eq2:In" }
                ]
            }
	        audio.channels = 2
	        audio.position = [ FL FR ]
            capture.props = {
                node.name   = "Explorer_in"
                media.class = Audio/Sink
            }
            playback.props = {
                node.name   = "Explorer_out"
                node.passive = true
            }
        }
    }
]
