# Paramatric EQ for AFUL Performer 5+2
#
# To activate, run $ pactl set-default-sink P5+2_in
#
context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "AFUL Performer 5+2"
            media.name       = "AFUL Performer 5+2"
            filter.graph = {
                nodes = [
                    {
                        type  = builtin
                        name  = eq0
                        label = bq_highshelf
                        control = { "Freq" = 0.0 "Q" = 1.0 "Gain" = -6.0 }
                    }
                    {
                        type = builtin
                        name = eq1
                        label = bq_peaking
                        control = { "Freq" = 10000 "Q" = 4 "Gain" = 5 }
                    }
                    {
                        type = builtin
                        name = eq2
                        label = bq_peaking
                        control = { "Freq" = 12000 "Q" = 3 "Gain" = 4 }
                    }
                ]
                links = [
                    { output = "eq0:Out" input = "eq1:In" }
                    { output = "eq1:Out" input = "eq2:In" }
                ]
            }
	        audio.channels = 2
	        audio.position = [ FL FR ]
            capture.props = {
                node.name   = "P5+2_in"
                media.class = Audio/Sink
            }
            playback.props = {
                node.name   = "P5+2_out"
                node.passive = true
            }
        }
    }
]
